# Generated by Django 3.2.9 on 2021-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Full Name', max_length=500)),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['name', '-date_created'],
            },
        ),
    ]
