# Generated by Django 3.2.9 on 2021-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Task', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
