# Generated by Django 3.2.9 on 2021-11-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-date_created']},
        ),
    ]
